name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'help wanted' || github.event.label.name == 'bug：help wanted'
        uses: actions-cool/issues-helper@v2
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          comment-emoji: "+1, -1"
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please send your Pull Request to proper branch (feature branch for the new feature, master for bugfix and other changes), fill the [Pull Request Template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md) here, provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!
            你好 @${{ github.event.issue.user.login }}，我们完全同意你的提议/反馈，欢迎直接在此仓库 [创建一个 Pull Request](https://help.github.com/en/articles/creating-a-pull-request) 来解决这个问题。请将 Pull Request 发到正确的分支（新特性发到 feature 分支，其他发到 master 分支），务必填写 Pull Request 内的[预设模板](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)，提供改动所需相应的 changelog、TypeScript 定义、测试用例、文档等，并确保 CI 通过，我们会尽快进行 Review，提前感谢和期待您的贡献。
            ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)

      - name: need repo
        if: github.event.label.name == 'Need Reproduce'
        uses: actions-cool/issues-helper@v2
        with:
          actions: "create-comment"
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide a online reproduction by forking this link  [react template](https://codesandbox.io/s/react-vant-template-eez7b) [nextjs template](https://codesandbox.io/s/react-vant-nextjs-template-uepyw) or a minimal GitHub repository. Issues labeled by \`Need Reproduce\` will be closed if no activities in 7 days.
            你好 @${{ github.event.issue.user.login }}, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击  [react template](https://codesandbox.io/s/react-vant-template-eez7b) [nextjs template](https://codesandbox.io/s/react-vant-nextjs-template-uepyw) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
            ![](https://gw.alipayobjects.com/zos/antfincdn/y9kwg7DVCd/reproduce.gif)

      - name: bug
        if: github.event.label.name == 'bug'
        uses: actions-cool/issues-helper@v2
        with:
          actions: "create-comment"
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. This is a bug, we will fix it as soon as possible.
            你好 @${{ github.event.issue.user.login }}, 这已经确定是一个bug，我们会尽快修复它。

      - name: processing
        if: github.event.label.name == 'processing'
        uses: actions-cool/issues-helper@v2
        with:
          actions: "create-comment"
          issue-number: ${{ github.event.issue.number }}
          body: |
            该issues目前正在处理中，处理过程可能需要你提供更多的信息，感谢你的配合

      - name: remove labels
        if: github.event.label.name == 'remove-labels'
        uses: actions-cool/issues-helper@v2
        with:
          actions: "remove-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "x1,x2"
