name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'help wanted' || github.event.label.name == 'bugï¼šhelp wanted'
        uses: actions-cool/issues-helper@up
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          comment-emoji: '+1, -1'
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please send your Pull Request to proper branch (feature branch for the new feature, master for bugfix and other changes), fill the [Pull Request Template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md) here, provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæˆ‘ä»¬å®Œå…¨åŒæ„ä½ çš„æè®®/åé¦ˆï¼Œæ¬¢è¿ç›´æ¥åœ¨æ­¤ä»“åº“ [åˆ›å»ºä¸€ä¸ª Pull Request](https://help.github.com/en/articles/creating-a-pull-request) æ¥è§£å†³è¿™ä¸ªé—®é¢˜ã€‚è¯·å°† Pull Request å‘åˆ°æ­£ç¡®çš„åˆ†æ”¯ï¼ˆæ–°ç‰¹æ€§å‘åˆ° feature åˆ†æ”¯ï¼Œå…¶ä»–å‘åˆ° master åˆ†æ”¯ï¼‰ï¼ŒåŠ¡å¿…å¡«å†™ Pull Request å†…çš„[é¢„è®¾æ¨¡æ¿](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)ï¼Œæä¾›æ”¹åŠ¨æ‰€éœ€ç›¸åº”çš„ changelogã€TypeScript å®šä¹‰ã€æµ‹è¯•ç”¨ä¾‹ã€æ–‡æ¡£ç­‰ï¼Œå¹¶ç¡®ä¿ CI é€šè¿‡ï¼Œæˆ‘ä»¬ä¼šå°½å¿«è¿›è¡Œ Reviewï¼Œæå‰æ„Ÿè°¢å’ŒæœŸå¾…æ‚¨çš„è´¡çŒ®ã€‚
            ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)

      - name: need repo
        if: github.event.label.name == 'ğŸ¤” Need Reproduce'
        uses: actions-cool/issues-helper@up
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by \`Need Reproduce\` will be closed if no activities in 7 days.
            ä½ å¥½ @${{ github.event.issue.user.login }}, æˆ‘ä»¬éœ€è¦ä½ æä¾›ä¸€ä¸ªåœ¨çº¿çš„é‡ç°å®ä¾‹ä»¥ä¾¿äºæˆ‘ä»¬å¸®ä½ æ’æŸ¥é—®é¢˜ã€‚ä½ å¯ä»¥é€šè¿‡ç‚¹å‡» [æ­¤å¤„](https://u.ant.design/codesandbox-repro) åˆ›å»ºä¸€ä¸ª codesandbox æˆ–è€…æä¾›ä¸€ä¸ªæœ€å°åŒ–çš„ GitHub ä»“åº“ã€‚7 å¤©å†…æœªè·Ÿè¿›çš„ issue å°†ä¼šè¢«è‡ªåŠ¨å…³é—­ã€‚
            ![](https://gw.alipayobjects.com/zos/antfincdn/y9kwg7DVCd/reproduce.gif)

      - name: remove labels
        if: github.event.label.name == 'remove-labels'
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'x1,x2'

      - name: duplicate
        if: github.event.label.name == 'duplicate'
        uses: actions-cool/issues-helper@up
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          comment-emoji: '+1, -1'
          labels: 'x1,x2'
          
      - name: add-assignees-1
        if: github.event.label.name == 'add-assignees-1'
        uses: actions-cool/issues-helper@up
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: 'xrkffgg,zoo-js-bot,HuaRin'
          random-to: 1
          
      - name: add-assignees-2
        if: github.event.label.name == 'add-assignees-2'
        uses: actions-cool/issues-helper@up
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: 'xrkffgg,zoo-js-bot,HuaRin'
          random-to: 2
          
      - name: lock
        if: github.event.label.name == 'lock-issue'
        uses: actions-cool/issues-helper@up
        with:
          actions: 'lock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          issue-emoji: '+1, -1'
          lock-reason: 'too heated'
